# Generated by Django 6.0.1 on 2026-01-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='objectives',
            field=models.TextField(blank=True, default='', verbose_name='Objectifs de la formation'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 1'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 2'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 3'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 4'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 5'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_pratique',
            field=models.TextField(blank=True, default='', verbose_name='Programme pratique détaillé'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Structure JSON du programme théorique et pratique', verbose_name='Structure du programme'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_theorique',
            field=models.TextField(blank=True, default='', verbose_name='Programme théorique détaillé'),
        ),
        migrations.AddField(
            model_name='training',
            name='schedule_json',
            field=models.JSONField(blank=True, default=list, help_text='Calendrier JSON des sessions', verbose_name='Calendrier de formation'),
        ),
    ]
