# Generated by Django 6.0.1 on 2026-01-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0002_training_objectives_training_prerequisite_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='programme_pdf_url',
            field=models.URLField(blank=True, help_text='Lien vers le fichier PDF du programme détaillé', max_length=500, null=True, verbose_name='URL du programme PDF'),
        ),
    ]
