# Generated by Django 6.0.1 on 2026-01-27 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0003_training_programme_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la promotion')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('original_price_mad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix original (MAD)')),
                ('promotional_price_mad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix promotionnel (MAD)')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='Pourcentage de réduction')),
                ('background_color', models.CharField(default='#34745C', max_length=50, verbose_name='Couleur de fond')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=50, verbose_name='Couleur du texte')),
                ('badge_text', models.CharField(default='PROMO', max_length=50, verbose_name='Texte du badge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_until', models.DateField(verbose_name="Valide jusqu'au")),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='Utilisations maximum')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations actuelles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diray.training', verbose_name='Formation associée')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('payment_method', models.CharField(choices=[('card', 'Carte bancaire'), ('transfer', 'Virement bancaire'), ('mobile', 'Mobile Money'), ('paypal', 'PayPal')], max_length=50, verbose_name='Méthode de paiement')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='4 derniers chiffres de la carte')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID de transaction')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('original_price_mad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix original (MAD)')),
                ('paid_price_mad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé (MAD)')),
                ('currency_used', models.CharField(default='MAD', max_length=3, verbose_name='Devise utilisée')),
                ('receipt_generated', models.BooleanField(default=False, verbose_name='Reçu généré')),
                ('receipt_pdf_url', models.URLField(blank=True, max_length=500, verbose_name='URL du reçu PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID de session')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presubscriptions', to='diray.training', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Pré-inscription',
                'verbose_name_plural': 'Pré-inscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['training', 'payment_status'], name='diray_train_trainin_6a6747_idx'), models.Index(fields=['email', 'created_at'], name='diray_train_email_4e0335_idx'), models.Index(fields=['transaction_id'], name='diray_train_transac_0975a7_idx')],
            },
        ),
    ]
