# Generated by Django 6.0.1 on 2026-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0004_promotion_trainingpresubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='DIRAY CENTRE', max_length=200, verbose_name='Nom de la société')),
                ('bank_name', models.CharField(default='Attijariwafa Bank', max_length=200, verbose_name='Nom de la banque')),
                ('account_holder', models.CharField(default='DIRAY CENTRE', max_length=200, verbose_name='Titulaire du compte')),
                ('rib', models.CharField(max_length=50, verbose_name="RIB (Relevé d'Identité Bancaire)")),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('swift_bic', models.CharField(blank=True, max_length=20, verbose_name='Code SWIFT/BIC')),
                ('branch_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'agence")),
                ('branch_code', models.CharField(blank=True, max_length=20, verbose_name='Code agence')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('confirmation_email', models.EmailField(default='contact@diraycentre.ma', max_length=254, verbose_name='Email de confirmation')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': "Compte bancaire d'entreprise",
                'verbose_name_plural': "Comptes bancaires d'entreprise",
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, verbose_name='4 derniers chiffres carte'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Paiement sur place')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='transfer_receipt_notes',
            field=models.TextField(blank=True, verbose_name='Notes sur le reçu'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='transfer_receipt_uploaded',
            field=models.BooleanField(default=False, verbose_name='Reçu de virement uploadé'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='transfer_receipt_verified',
            field=models.BooleanField(default=False, verbose_name='Reçu de virement vérifié'),
        ),
    ]
