# Generated by Django 6.0.1 on 2026-01-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0005_companybankaccount_contactrequest_card_last_four_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactrequest',
            name='diray_conta_is_thre_78c088_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactrequest',
            name='diray_conta_ip_addr_b7a270_idx',
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, verbose_name="Date d'expiration"),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='transfer_confirmation',
            field=models.TextField(blank=True, verbose_name='Confirmation de virement'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du virement'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence virement'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='transfer_screenshot_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL capture virement'),
        ),
        migrations.AddField(
            model_name='trainingpresubscription',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, verbose_name="Date d'expiration"),
        ),
        migrations.AddField(
            model_name='trainingpresubscription',
            name='transfer_confirmation',
            field=models.TextField(blank=True, verbose_name='Confirmation de virement'),
        ),
        migrations.AddField(
            model_name='trainingpresubscription',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence virement'),
        ),
        migrations.AlterField(
            model_name='companybankaccount',
            name='whatsapp_number',
            field=models.CharField(default='+212779259942', max_length=20, verbose_name='Numéro WhatsApp'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('processing', 'En traitement'), ('completed', 'Traité'), ('archived', 'Archivé')], default='new', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='trainingpresubscription',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Paiement sur place')], max_length=50, verbose_name='Méthode de paiement'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['payment_method', 'payment_status'], name='diray_conta_payment_a65866_idx'),
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='current_country',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='pages_visited',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='target_country',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='time_on_site',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='transfer_receipt_notes',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='transfer_receipt_uploaded',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='transfer_receipt_verified',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='viewed_pricing',
        ),
    ]
