# Generated by Django 6.0.1 on 2026-01-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0006_remove_contactrequest_diray_conta_is_thre_78c088_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='badge_text_ar',
            field=models.CharField(blank=True, default='عرض', max_length=50, verbose_name='نص الشارة AR'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='badge_text_en',
            field=models.CharField(blank=True, default='PROMO', max_length=50, verbose_name='Badge text EN'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description AR'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description EN'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='subtitle_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sous-titre AR'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtitle EN'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre de la promotion AR'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Promotion title EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_desc_1_ar',
            field=models.TextField(blank=True, verbose_name='Certificat 1 - Description AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_desc_1_en',
            field=models.TextField(blank=True, verbose_name='Certificat 1 - Description EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_desc_2_ar',
            field=models.TextField(blank=True, verbose_name='Certificat 2 - Description AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_desc_2_en',
            field=models.TextField(blank=True, verbose_name='Certificat 2 - Description EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_desc_3_ar',
            field=models.TextField(blank=True, verbose_name='Certificat 3 - Description AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_desc_3_en',
            field=models.TextField(blank=True, verbose_name='Certificat 3 - Description EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_name_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 1 - Nom AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_name_1_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 1 - Nom EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_name_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 2 - Nom AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_name_2_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 2 - Nom EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_name_3_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 3 - Nom AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_name_3_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 3 - Nom EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='detailed_description_ar',
            field=models.TextField(blank=True, verbose_name='Description détaillée AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='detailed_description_en',
            field=models.TextField(blank=True, verbose_name='Description détaillée EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_1_ar',
            field=models.TextField(blank=True, verbose_name='جواب FAQ 1 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_1_en',
            field=models.TextField(blank=True, verbose_name='FAQ Answer 1 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_2_ar',
            field=models.TextField(blank=True, verbose_name='جواب FAQ 2 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_2_en',
            field=models.TextField(blank=True, verbose_name='FAQ Answer 2 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_3_ar',
            field=models.TextField(blank=True, verbose_name='جواب FAQ 3 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_3_en',
            field=models.TextField(blank=True, verbose_name='FAQ Answer 3 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_4_ar',
            field=models.TextField(blank=True, verbose_name='جواب FAQ 4 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_4_en',
            field=models.TextField(blank=True, verbose_name='FAQ Answer 4 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_5_ar',
            field=models.TextField(blank=True, verbose_name='جواب FAQ 5 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_answer_5_en',
            field=models.TextField(blank=True, verbose_name='FAQ Answer 5 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_1_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='سؤال FAQ 1 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_1_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 1 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_2_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='سؤال FAQ 2 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_2_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 2 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_3_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='سؤال FAQ 3 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_3_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 3 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_4_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='سؤال FAQ 4 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_4_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 4 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_5_ar',
            field=models.CharField(blank=True, max_length=300, verbose_name='سؤال FAQ 5 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='faq_question_5_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 5 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='خاصية 1 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_1_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Feature 1 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='خاصية 2 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_2_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Feature 2 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_3_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='خاصية 3 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_3_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Feature 3 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_4_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='خاصية 4 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_4_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Feature 4 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_5_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='خاصية 5 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='feature_5_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Feature 5 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 1 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_1_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 1 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 2 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_2_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 2 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_3_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 3 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_3_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 3 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_4_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 4 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_4_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 4 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_5_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 5 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='gallery_caption_5_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 5 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='objectives_ar',
            field=models.TextField(blank=True, default='', verbose_name='Objectifs AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='objectives_en',
            field=models.TextField(blank=True, default='', verbose_name='Objectifs EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_1_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='المتطلبات المسبقة 1 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_1_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prerequisite 1 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_2_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='المتطلبات المسبقة 2 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_2_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prerequisite 2 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_3_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='المتطلبات المسبقة 3 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_3_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prerequisite 3 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_4_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='المتطلبات المسبقة 4 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_4_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prerequisite 4 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_5_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='المتطلبات المسبقة 5 AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisite_5_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prerequisite 5 EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_pratique_ar',
            field=models.TextField(blank=True, default='', verbose_name='Programme pratique AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_pratique_en',
            field=models.TextField(blank=True, default='', verbose_name='Programme pratique EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_structure_ar',
            field=models.JSONField(blank=True, default=dict, help_text='Structure JSON du programme théorique et pratique AR', verbose_name='Structure du programme AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_structure_en',
            field=models.JSONField(blank=True, default=dict, help_text='Structure JSON du programme théorique et pratique EN', verbose_name='Structure du programme EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_theorique_ar',
            field=models.TextField(blank=True, default='', verbose_name='Programme théorique AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='programme_theorique_en',
            field=models.TextField(blank=True, default='', verbose_name='Programme théorique EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='short_description_ar',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description courte AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description courte EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='slug_ar',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_average_salary_ar',
            field=models.CharField(blank=True, default='٨٥٠٠ درهم', max_length=50, verbose_name='Salaire moyen AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_average_salary_en',
            field=models.CharField(blank=True, default='8500 MAD', max_length=50, verbose_name='Average salary EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_company_partnerships_ar',
            field=models.CharField(blank=True, default='٥٠+', max_length=50, verbose_name='Entreprises partenaires AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_company_partnerships_en',
            field=models.CharField(blank=True, default='50+', max_length=50, verbose_name='Company partnerships EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_employment_rate_ar',
            field=models.CharField(blank=True, default='٪٩٥', max_length=50, verbose_name="Taux d'emploi AR"),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_employment_rate_en',
            field=models.CharField(blank=True, default='95%', max_length=50, verbose_name='Employment rate EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_exam_success_ar',
            field=models.CharField(blank=True, default='٪٩٨', max_length=50, verbose_name='Taux de réussite AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_exam_success_en',
            field=models.CharField(blank=True, default='98%', max_length=50, verbose_name='Exam success rate EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_student_satisfaction_ar',
            field=models.CharField(blank=True, default='٤٫٨/٥', max_length=50, verbose_name='Satisfaction AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='stat_student_satisfaction_en',
            field=models.CharField(blank=True, default='4.8/5', max_length=50, verbose_name='Student satisfaction EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_name_1_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='شاهد 1 - اسم AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_name_1_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Witness 1 - Name EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_name_2_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='شاهد 2 - اسم AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_name_2_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Witness 2 - Name EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_name_3_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='شاهد 3 - اسم AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_name_3_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Witness 3 - Name EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_position_1_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='شاهد 1 - منصب AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_position_1_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Witness 1 - Position EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_position_2_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='شاهد 2 - منصب AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_position_2_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Witness 2 - Position EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_position_3_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='شاهد 3 - منصب AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_position_3_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Witness 3 - Position EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_review_1_ar',
            field=models.TextField(blank=True, verbose_name='شاهد 1 - شهادة AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_review_1_en',
            field=models.TextField(blank=True, verbose_name='Witness 1 - Testimonial EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_review_2_ar',
            field=models.TextField(blank=True, verbose_name='شاهد 2 - شهادة AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_review_2_en',
            field=models.TextField(blank=True, verbose_name='Witness 2 - Testimonial EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_review_3_ar',
            field=models.TextField(blank=True, verbose_name='شاهد 3 - شهادة AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='testimonial_review_3_en',
            field=models.TextField(blank=True, verbose_name='Witness 3 - Testimonial EN'),
        ),
        migrations.AddField(
            model_name='training',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre AR'),
        ),
        migrations.AddField(
            model_name='training',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre EN'),
        ),
        migrations.AlterField(
            model_name='training',
            name='certificate_desc_1',
            field=models.TextField(blank=True, verbose_name='Certificat 1 - Description FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='certificate_desc_2',
            field=models.TextField(blank=True, verbose_name='Certificat 2 - Description FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='certificate_desc_3',
            field=models.TextField(blank=True, verbose_name='Certificat 3 - Description FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='certificate_name_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 1 - Nom FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='certificate_name_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 2 - Nom FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='certificate_name_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Certificat 3 - Nom FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='detailed_description',
            field=models.TextField(verbose_name='Description détaillée FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_answer_1',
            field=models.TextField(blank=True, verbose_name='FAQ Réponse 1 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_answer_2',
            field=models.TextField(blank=True, verbose_name='FAQ Réponse 2 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_answer_3',
            field=models.TextField(blank=True, verbose_name='FAQ Réponse 3 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_answer_4',
            field=models.TextField(blank=True, verbose_name='FAQ Réponse 4 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_answer_5',
            field=models.TextField(blank=True, verbose_name='FAQ Réponse 5 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_question_1',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 1 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_question_2',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 2 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_question_3',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 3 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_question_4',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 4 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='faq_question_5',
            field=models.CharField(blank=True, max_length=300, verbose_name='FAQ Question 5 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='feature_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fonctionnalité 1 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='feature_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fonctionnalité 2 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='feature_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fonctionnalité 3 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='feature_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fonctionnalité 4 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='feature_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fonctionnalité 5 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='gallery_caption_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 1 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='gallery_caption_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 2 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='gallery_caption_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 3 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='gallery_caption_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 4 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='gallery_caption_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende image 5 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='objectives',
            field=models.TextField(blank=True, default='', verbose_name='Objectifs FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='prerequisite_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 1 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='prerequisite_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 2 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='prerequisite_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 3 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='prerequisite_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 4 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='prerequisite_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Prérequis 5 FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='programme_pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL du programme PDF'),
        ),
        migrations.AlterField(
            model_name='training',
            name='programme_pratique',
            field=models.TextField(blank=True, default='', verbose_name='Programme pratique FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='programme_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Structure JSON du programme théorique et pratique FR', verbose_name='Structure du programme FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='programme_theorique',
            field=models.TextField(blank=True, default='', verbose_name='Programme théorique FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='short_description',
            field=models.TextField(max_length=300, verbose_name='Description courte FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='stat_average_salary',
            field=models.CharField(blank=True, default='8500 MAD', max_length=50, verbose_name='Salaire moyen FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='stat_company_partnerships',
            field=models.CharField(blank=True, default='50+', max_length=50, verbose_name='Entreprises partenaires FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='stat_employment_rate',
            field=models.CharField(blank=True, default='95%', max_length=50, verbose_name="Taux d'emploi FR"),
        ),
        migrations.AlterField(
            model_name='training',
            name='stat_exam_success',
            field=models.CharField(blank=True, default='98%', max_length=50, verbose_name='Taux de réussite FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='stat_student_satisfaction',
            field=models.CharField(blank=True, default='4.8/5', max_length=50, verbose_name='Satisfaction FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_name_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Témoin 1 - Nom FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_name_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Témoin 2 - Nom FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_name_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Témoin 3 - Nom FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_position_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Témoin 1 - Poste FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_position_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Témoin 2 - Poste FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_position_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Témoin 3 - Poste FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_review_1',
            field=models.TextField(blank=True, verbose_name='Témoin 1 - Témoignage FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_review_2',
            field=models.TextField(blank=True, verbose_name='Témoin 2 - Témoignage FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='testimonial_review_3',
            field=models.TextField(blank=True, verbose_name='Témoin 3 - Témoignage FR'),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Titre FR'),
        ),
    ]
