# Generated by Django 6.0.1 on 2026-01-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0007_promotion_badge_text_ar_promotion_badge_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingreview',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Avatar'),
        ),
    ]
