# Generated by Django 5.2.8 on 2026-01-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0009_profile_professorprofile_recordedvideo_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordedvideo',
            name='video_provider_id',
        ),
        migrations.AddField(
            model_name='liverecording',
            name='duration_seconds',
            field=models.IntegerField(default=0, verbose_name='Durée (secondes)'),
        ),
        migrations.AddField(
            model_name='liverecording',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500, verbose_name="URL de l'enregistrement"),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='professorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Spécialisation'),
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Vidéo (auprès du fournisseur)'),
        ),
        migrations.AddField(
            model_name='recordedvideo',
            name='video_provider',
            field=models.CharField(choices=[('VDOCIPHER', 'VdoCipher'), ('VIMEO', 'Vimeo'), ('YOUTUBE', 'YouTube'), ('OTHER', 'Autre')], default='VDOCIPHER', max_length=50, verbose_name='Fournisseur vidéo'),
        ),
        migrations.AlterField(
            model_name='liverecording',
            name='video_provider_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID Recording Provider'),
        ),
    ]
