# Generated by Django 5.2.8 on 2026-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0010_remove_recordedvideo_video_provider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cin_or_passport',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='CIN ou Passeport'),
        ),
    ]
