# Generated by Django 5.2.8 on 2026-01-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0013_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='diray.session'),
        ),
        migrations.AddField(
            model_name='notification',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='diray.session'),
        ),
    ]
