# Generated by Django 5.2.8 on 2026-01-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0014_comment_session_notification_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='live_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='diray.livestream'),
        ),
        migrations.AddField(
            model_name='liverecording',
            name='live_stream',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='diray.livestream'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Créée'), ('ONGOING', 'En cours'), ('COMPLETED', 'Terminée')], default='CREATED', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='liverecording',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='diray.session'),
        ),
    ]
