# Generated by Django 5.2.8 on 2026-01-29 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0015_attendancelog_is_muted_attendancelog_live_stream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='training',
        ),
        migrations.AddField(
            model_name='session',
            name='trainings',
            field=models.ManyToManyField(related_name='sessions', to='diray.training', verbose_name='Formations'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Étudiant'), ('PROFESSOR', 'Professeur'), ('ASSISTANT', 'Assistant administratif'), ('ADMIN', 'Administrateur')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_cities', models.JSONField(blank=True, default=list, verbose_name='Villes assignées')),
                ('notes', models.TextField(blank=True, verbose_name='Notes administratives')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to='diray.profile')),
            ],
        ),
    ]
