# Generated by Django 5.2.8 on 2026-01-29 19:11

import django.db.models.deletion
from django.db import migrations, models


def migrate_cities_to_fks(apps, schema_editor):
    City = apps.get_model('diray', 'City')
    Profile = apps.get_model('diray', 'Profile')
    Session = apps.get_model('diray', 'Session')
    AssistantProfile = apps.get_model('diray', 'AssistantProfile')
    
    # 1. Map Profiles
    for p in Profile.objects.all():
        if p.city_old:
            city_obj = City.objects.filter(name__iexact=p.city_old).first()
            if city_obj:
                p.city = city_obj
                p.save()
                
    # 2. Map Sessions
    for s in Session.objects.all():
        if s.city_old:
            city_obj = City.objects.filter(name__iexact=s.city_old).first()
            if city_obj:
                s.city = city_obj
                s.save()

    # 3. Map Assistant Profiles (JSON to ManyToMany)
    for ap in AssistantProfile.objects.all():
        if ap.assigned_cities_old:
            for city_name in ap.assigned_cities_old:
                city_obj = City.objects.filter(name__iexact=city_name).first()
                if city_obj:
                    ap.assigned_cities.add(city_obj)

class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0016_remove_session_training_session_trainings_and_more'),
    ]

    operations = [
        # Rename existing fields to _old
        migrations.RenameField(model_name='profile', old_name='city', new_name='city_old'),
        migrations.RenameField(model_name='session', old_name='city', new_name='city_old'),
        migrations.RenameField(model_name='assistantprofile', old_name='assigned_cities', new_name='assigned_cities_old'),
        
        # Add new fields as NULLable
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diray.city', verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='session',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diray.city', verbose_name='Ville de la session'),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='assigned_cities',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='diray.city', verbose_name='Villes assignées'),
        ),
        
        # Run data migration
        migrations.RunPython(migrate_cities_to_fks),
        
        # Remove old fields
        migrations.RemoveField(model_name='profile', name='city_old'),
        migrations.RemoveField(model_name='session', name='city_old'),
        migrations.RemoveField(model_name='assistantprofile', name='assigned_cities_old'),
    ]
