# Generated by Django 5.2.8 on 2026-01-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0017_remove_assistantprofile_assigned_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Répondu'),
        ),
    ]
