# Generated by Django 5.2.8 on 2026-01-30 01:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0018_comment_is_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='trainings',
            new_name='formations',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='formations_access',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='sessions_access',
        ),
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='authorized_formations',
            field=models.ManyToManyField(blank=True, related_name='students', to='diray.training', verbose_name='Formations autorisées'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='diray.session', verbose_name='Session active'),
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('agora_channel', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lives', to='diray.session')),
            ],
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='live_stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='diray.live'),
        ),
        migrations.AlterField(
            model_name='liverecording',
            name='live_stream',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='diray.live'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('answer_content', models.TextField(blank=True, verbose_name='Réponse')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Répondu')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to='diray.professorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diray.studentprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diray.recordedvideo')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='LiveStream',
        ),
    ]
