# Generated by Django 6.0.1 on 2026-01-30 13:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0019_remove_livestream_session_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant total dû'),
        ),
        migrations.AlterField(
            model_name='assistantprofile',
            name='profile',
            field=models.OneToOneField(limit_choices_to={'role': 'ASSISTANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to='diray.profile'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='diray.profile'),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='profile',
            field=models.OneToOneField(limit_choices_to={'role': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to='diray.profile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile',
            field=models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='diray.profile'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='diray.profile'),
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la séance')),
                ('type', models.CharField(choices=[('THEORIQUE', 'Théorique'), ('PRATIQUE', 'Pratique')], default='THEORIQUE', max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Heure')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu/Salle')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='diray.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date', 'time'],
            },
        ),
    ]
