# Generated by Django 6.0.1 on 2026-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diray', '0020_studentprofile_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Photo de profil'),
        ),
    ]
